live_config_reload = false

[colors]
transparent_background_colors = true

[cursor]
thickness = 0.0
unfocused_hollow = true
vi_mode_style = "Block"

[cursor.style]
blinking = "Never"
shape = "Beam"

[font]
size = 13.0

[font.bold]
family = "firacode"
style = "Bold"

[font.bold_italic]
family = "firacode"
style = "Bold Italic"

[font.italic]
family = "firacode"
style = "Italic"

[font.normal]
family = "firacode"
style = "Regular"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "none"
decorations_theme_variant = "Dark"
opacity = 0.66

[window.padding]
x = 20
y = 20
