
[general]
import = [
  "~/magit/dotfiles/catppuccin-mocha.toml"
]
live_config_reload = false

[cursor]
thickness = 0.2
unfocused_hollow = true
vi_mode_style = "Block"

[cursor.style]
blinking = "Never"
shape = "Beam"

[font]
size = 13.0

[font.bold]
family = "firacode"
style = "Bold"

[font.bold_italic]
family = "firacode"
style = "Bold Italic"

[font.italic]
family = "firacode"
style = "Italic"

[font.normal]
family = "firacode"
style = "Regular"

[terminal.shell]
program = "nu"
args = [
  "--config",
  "~/magit/dotfiles/nushell/config.nu",
  "--env-config",
  "~/magit/dotfiles/nushell/env.nu"
]

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "none"
decorations_theme_variant = "Dark"
opacity = 0.8
