theme= deep
command=nu --no-std-lib --config ~/magit/dotfiles/nushell/config.nu --env-config ~/magit/dotfiles/nushell/env.nu
background-opacity=0.8
font-size=14
font-family="fira code"
copy-on-select=true
window-decoration=false
keybind=alt+t=new_tab
keybind=alt+p=toggle_tab_overview
