theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = false
shell = ["nu","--stdin","-c"]

[editor.lsp]
display-messages = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'
"'" = "'"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.insert]
C-i = "normal_mode"
A-k = ":bc"
A-K = ":bc!"

[keys.normal]
C-j = "scroll_up"
C-k = "scroll_down"
A-k = ":bc"
A-K = ":bc!"

[keys.normal.space.m]
g = [":new", ":insert-output gitu", ":buffer-close!", ":redraw"] 
f = [":new", ":insert-output joshuto", ":buffer-close!", ":redraw"]
