theme = "ayu_dark"

[editor]
line-number = "relative"
mouse = false

[editor.lsp]
display-messages = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.insert]
"A-j" = "normal_mode"

[keys.normal."C-t"]
f = ":pipe deno fmt -"

[keys.normal."C-r"]
b = ":sh cargo build"

[keys.normal.z]
j = "scroll_up"
k = "scroll_down"
