theme = "ayu_dark"

[editor]
line-number = "relative"
mouse = false
shell = ["nu","--stdin","-c"]

[editor.lsp]
display-messages = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'
"'" = "'"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.insert]
"A-j" = "normal_mode"
"A-k" = ":bc"
"A-K" = ":bc!"

[keys.normal]
"A-k" = ":bc"
"A-K" = ":bc!"

[keys.normal.z]
j = "scroll_up"
k = "scroll_down"
