[[language]]
name = "rust"
indent = { tab-width = 2,unit = " "}
shebangs = ["cargo -Zscript"]
diagnostic-severity = "Hint"
# auto-format = false

[language-server.rust-analyzer.config.check]
command = "clippy"


[[language]]
name = "typescript"
indent = { tab-width = 2,unit = " "}
diagnostic-severity = "Hint"

